### ISSUE TITLE
Failing dependency

### ISSUE THREAD

**Issue by JohnZonneveld** [jawatson/pythonprop#9]
Tried to install this under Raspbian Buster but it fails as the python3-matplotlib-gtk3 package cannot be located.
Haven't found a way yet to install it another way.

**Comment by jaredd** [comment]
I was able to get this working in a buster docker container, but I had to:
1) use python 3.7, python 3.8 had some unexplained numpy errors both from Debian package and pip.
2) my package list:
      gir1.2-gtk-3.0 \
      gobject-introspection \
      python3-cairocffi \
      python3-cartopy \
      python3-gi-cairo \
      python3-matplotlib \
      python3-numpy \
      python3-scipy \
      python3-tk \
3) add PYTHONPATH=/usr/lib/python3/dist-packages -- this could be an issue with the base container image, not sure

**Comment by jaredd** [comment]
I also found some issues with the autoconf setup while building the docker image, mostly related to the document generation. I followed [this gnome reference](https://developer.gnome.org/gnome-doc-make/unstable/migrating.html.en) to update some files. The overall patch that builds PythonProp v0.29 on buster is attached. During the build process I also had to configure with 
```
$ configure --disable-scrollkeeper
```
[buster.patch.txt](https://github.com/jawatson/pythonprop/files/4664252/buster.patch.txt)

**Comment by jawatson** [comment]
Thanks for this and the pdf fix.  I've rather let things slip with this and spend most of my limited free time working on the rec533 prediction engine at https://soundbytes.asia/proppy/p2p I have a week off work and will include the changes in the next release - hoping by the end of the week.

**Comment by jaredd** [comment]
Thanks for the comment. So should we as HF radio people start moving away
from VOACAP and to ITURHFPROP? I tried the link to the latter on
https://soundbytes.asia/proppy/help/about and it drops me at a login
screen. Is it closed source?

**Comment by jawatson** [comment]
After implementing the fixes, I spun up Ubuntu 20.04 on a virtual machine and found that the gnome-doc-utils package is no longer available form the standard repos.  The repos for 19.10 tag the package as deprecated.  Looking at the dates on the documentation pages it looks like it's not really actively supported.  I seem to recall now that why I removed it all in the v0.30(beta2) build.  It looks like a long term fix will be to build the documentation and browse it using yelp directly. 

As for rec533 vs voacap... Rec533s prediction engine appears to yield better results than voacap (using the methodology of the ITU's own Rec.P.1148).  However, rec533 does not currently support the range of antennas supported by voacap making system modelling a little harder.

**Comment by jaredd** [comment]
I'm not a gnome expert in any way, so I don't have a great solution to this right now. 

But would you recommend going to rec533 then? Is there a better place to get it than [the ITS site](https://www.its.bldrdoc.gov/resources/radio-propagation-software/high-frequency/rec533-propagation-model.aspx)? This is dated 2005, which I can't believe is the most updated version. It also has a lot of caveats for compiling. NTIA has a whole github presence, how come this code isn't included? Would you have any advice for porting rec533 to Linux?

**Comment by jawatson** [comment]
I've just released another beta (v0.3b5) which moves everything to yelp-tools which is Gnome's preferred way of doing things these days it seems.  It installs without issues on a minimal installation of Ubuntu 20.04 - I'll leave it for a couple of days then push out a proper release.

https://wiki.gnome.org/Initiatives/GnomeGoals/NewDocumentationInfrastructure

I use the ITU's version of REC533 (ITURHFProp) as it's actively maintained by a recognised body.  It's closed source at the moment as they don't want to control the source and avoid a repeat of voacap which has a number of versions, some of which have been modified.  Look for the ITUURHF row in the table at the following link.

https://www.itu.int/en/ITU-R/study-groups/rsg3/Pages/iono-tropo-spheric.aspx

**Comment by jaredd** [comment]
"It's closed source at the moment as they don't want to control the
source..."

Based on the rest of that sentence I am assuming that you mean the ITU
doesn't want to be responsible for forks? The statement itself seems a
little contradictory. There may be license options here to include a
pointer back to the original or (less community-oriented) to disallow
forks. It's a shame that this code is not more accessible. It's also
unfortunate that this is strictly a win binary. Do you know if the link
labeled "source of REC533" here
https://www.its.bldrdoc.gov/resources/radio-propagation-software/high-frequency/high-frequency-propagation-models.aspx
is genuine? I would be interested in getting a Linux version of this
running.

**Comment by jawatson** [comment]
There should be  Linux binary in the download at the ITU's site that I referenced previously.  I worked with the ITU to get it running on Linux and it's used on my website.
The version of the REC533 at the Boulder site is an earlier version that was written in Fortran (the ITU's version is written in C).  Both are based on ITU's Rec.P533.  The ITU's version is maintained and corresponds to the latest version of the standard, I'm not sure which version Boulder's implementation stops at.  
We're getting way off topic here so please feel free to email me directly to discuss this further using the address at the foot of my website.

**Comment by jawatson** [comment]
If python dependencies aren't available from system repos, they may be installed using pip as noted by Jarredd above.
